### ISSUE TITLE
Network plugin "calico" failed init: exit status 255

### ISSUE THREAD

**Issue by Smana** [projectcalico/calico-kubernetes#27]
Hello,

I'm currently testing calico with kubernetes but i'm facing an issue.
I followed the documentation : https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu-calico.md

And calico seems to be happy : 
```
calicoctl status
calico-node container is running. Status: Up 36 minutes

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| Peer address |     Peer type     | State |  Since   |     Info    |
+--------------+-------------------+-------+----------+-------------+
| 10.115.77.88 | node-to-node mesh |   up  | 12:57:29 | Established |
| 10.115.77.89 | node-to-node mesh |   up  | 12:58:48 | Established |
| 10.115.77.87 | node-to-node mesh |   up  | 12:58:40 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
+--------------+-----------+-------+-------+------+
| Peer address | Peer type | State | Since | Info |
+--------------+-----------+-------+-------+------+
+--------------+-----------+-------+-------+------+
```
The containers can talk each others from node to node.

Unfortunately when i start kubelet on nodes i get the following message : 
```
/usr/local/bin/kubelet --logtostderr=true --v=0 --api_servers=https://10.115.77.86:443 --address=0.0.0.0 --hostname_override=10.115.77.87 --allow_privileged=true --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --network_plugin=calico
I0827 13:37:12.027317     935 manager.go:127] cAdvisor running in container: "/"
I0827 13:37:12.028076     935 fs.go:93] Filesystem partitions: map[/dev/vda2:{mountpoint:/ major:254 minor:2}]
I0827 13:37:12.031702     935 manager.go:156] Machine: {NumCores:2 CpuFrequency:2260998 MemoryCapacity:3167059968 MachineID:c39561d3284963021ae3cb2b995631a5 SystemUUID:7869686E-14AA-25EA-A478-2454DC0FA17A BootID:af96ffa8-08d3-45cd-b799-c1e7f8441f18 Filesystems:[{Device:/dev/vda2 Capacity:31571550208}] DiskMap:map[254:0:{Name:vda Major:254 Minor:0 Size:32212254720 Scheduler:none}] NetworkDevices:[{Name:cbr0 MacAddress:4e:1f:03:44:18:a4 Speed:0 Mtu:1500} {Name:eth0 MacAddress:52:54:00:d7:32:b7 Speed:0 Mtu:1500} {Name:tunl0 MacAddress:00:00:00:00 Speed:0 Mtu:1480}] Topology:[{Id:0 Memory:3167059968 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:1 Memory:0 Cores:[{Id:0 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}]}
I0827 13:37:12.033000     935 manager.go:163] Version: {KernelVersion:3.16.0-4-amd64 ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.6.2 CadvisorVersion:0.15.1}
I0827 13:37:12.033851     935 plugins.go:69] No cloud provider specified.
I0827 13:37:13.065601     935 docker.go:295] Connecting to docker on unix:///var/run/docker.sock
I0827 13:37:13.066002     935 server.go:673] Watching apiserver
failed to create kubelet: Network plugin "calico" failed init: exit status 255
```

Could you please help me to find out how to get it work ?

Some information : 
docker version : 1.6.2 (i know it is not the latest, tell me if that could be the cause)
calicoctl version : 0.5.1
kubernetes version : 1.0.3
OS : debian jessie

Thanks,
Smana

**Comment by Smana** [comment]
Given kubernetes's code this error is raised when the plugin can't be loaded.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/plugins.go

But i don't know how to proceed

**Comment by Smana** [comment]
i've posted the issue in the kubernetes github too because  the error comes from kubelet. i'll let you know

**Comment by caseydavenport** [comment]
Hi Smana,

Could you check the contents of the following command:
```
ls -la /usr/libexec/kubernetes/kubelet-plugins/net/exec/calico/calico
```

The most likely culprit when the plugin fails init is that the plugin binary doesn't have executable permissions.

**Comment by caseydavenport** [comment]
If the binary does have executable permissions, could you modify your kubelet parameters to enable verbose logging?  It might give a clearer picture of why the plugin is failing `init`

You can do this by setting the `--v=5` flag when starting the kubelet.

**Comment by Smana** [comment]
Thanks @caseydavenport.
I just installed kubernetes binaries...
i'm going to check how to install properly the plugins.
i keep you updated

**Comment by Smana** [comment]
Thanks for your, that was exactly what i needed :)

```
Aug 28 06:57:42 kubenode-2 kubelet[7143]: I0828 06:57:42.515935    7143 server.go:273] Using root directory: /var/lib/kubelet
Aug 28 06:57:42 kubenode-2 kubelet[7143]: I0828 06:57:42.516221    7143 manager.go:127] cAdvisor running in container: "/"
Aug 28 06:57:42 kubenode-2 kubelet[7143]: I0828 06:57:42.517107    7143 fs.go:93] Filesystem partitions: map[/dev/vda2:{mountpoint:/ major:254 minor:2}]
Aug 28 06:57:42 kubenode-2 kubelet[7143]: I0828 06:57:42.520807    7143 manager.go:156] Machine: {NumCores:2 CpuFrequency:2260998 MemoryCapacity:3167059968 MachineID:c39561d3284963021ae3cb2b995631a5 SystemUUID:F4B216BC-269E-91A9-CF70-4023C73ABA15 BootID:9a9787b1-6de5-42f0-95d6-20248318742a Filesystems:[{Device:/dev/vda2 Capacity:31571550208}] DiskMap:map[254:0:{Name:vda Major:254 Minor:0 Size:32212254720 Scheduler:none}] NetworkDevices:[{Name:cbr0 MacAddress:82:99:04:e3:94:e9 Speed:0 Mtu:1500} {Name:eth0 MacAddress:52:54:00:92:fd:42 Speed:0 Mtu:1500} {Name:tunl0 MacAddress:00:00:00:00 Speed:0 Mtu:1480}] Topology:[{Id:0 Memory:3167059968 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]} {Id:1 Memory:0 Cores:[{Id:0 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}]}
Aug 28 06:57:42 kubenode-2 kubelet[7143]: I0828 06:57:42.523215    7143 manager.go:163] Version: {KernelVersion:3.16.0-4-amd64 ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.6.2 CadvisorVersion:0.15.1}
Aug 28 06:57:42 kubenode-2 kubelet[7143]: I0828 06:57:42.524323    7143 plugins.go:69] No cloud provider specified.
Aug 28 06:57:42 kubenode-2 kubelet[7143]: I0828 06:57:42.524426    7143 server.go:292] Successfully initialized cloud provider: "" from the config file: ""
Aug 28 06:57:43 kubenode-2 kubelet[7143]: I0828 06:57:43.445646    7143 server.go:413] Using self-signed cert (/var/run/kubernetes/kubelet.crt, /var/run/kubernetes/kubelet.key)
Aug 28 06:57:43 kubenode-2 kubelet[7143]: I0828 06:57:43.445708    7143 docker.go:295] Connecting to docker on unix:///var/run/docker.sock
Aug 28 06:57:43 kubenode-2 kubelet[7143]: I0828 06:57:43.446202    7143 server.go:608] Sending events to api server.
Aug 28 06:57:43 kubenode-2 kubelet[7143]: I0828 06:57:43.446202    7143 server.go:673] Watching apiserver
Aug 28 06:57:43 kubenode-2 kubelet[7143]: I0828 06:57:43.493566    7143 config.go:253] Setting pods for source api : {[] 0 api}
Aug 28 06:57:43 kubenode-2 kubelet[7143]: I0828 06:57:43.682890    7143 exec.go:106] Init 'exec' network plugin output: Using ETCD_AUTHORITY=kubernetes-master:6666
Aug 28 06:57:43 kubenode-2 kubelet[7143]: Using CALICOCTL_PATH=/usr/bin/calicoctl
Aug 28 06:57:43 kubenode-2 kubelet[7143]: Traceback (most recent call last):
Aug 28 06:57:43 kubenode-2 kubelet[7143]: File "<string>", line 23, in <module>
Aug 28 06:57:43 kubenode-2 kubelet[7143]: File "/code/build/calico_kubernetes/out00-PYZ.pyz/sh", line 788, in __init__
Aug 28 06:57:43 kubenode-2 kubelet[7143]: sh.CommandNotFound: /usr/bin/calicoctl
Aug 28 06:57:43 kubenode-2 kubelet[7143]: , exit status 255
Aug 28 06:57:43 kubenode-2 kubelet[7143]: failed to create kubelet: Network plugin "calico" failed init: exit status 255
```

As all my binaries are installed in "/usr/local/bin/" i've just created a symlink.

Regards,
Smana

**Comment by Smana** [comment]
Hmmm, i just changed the kubelet systemd file. i've forgot the environment file.
