### ISSUE TITLE
Containers are not able to ping each others : "No JSON object could be decoded"

### ISSUE THREAD

**Issue by Smana** [projectcalico/calico-kubernetes#28]
Hello,

I think my kubelet service is properly configured now.
When i run a pod, the container gets its address from the pool
```
ip a show cbr0
5: cbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.233.1.1/24 scope global cbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::507b:20ff:fe97:c0cf/64 scope link 
       valid_lft forever preferred_lft forever

ps aux | grep /usr/bin/docker
/usr/bin/docker -d -H fd:// --bridge=cbr0 --iptables=false --ip-masq=false

docker exec k8s_worker.41ff1f2e_redis-slave-nruvk_default_08421053-4d68-11e5-af10-525400c14d0a_77d68d0f ip a show eth0
18: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:1b:00:d7:e0:27 brd ff:ff:ff:ff:ff:ff
    inet 10.233.1.5/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::501b:ff:fed7:e027/64 scope link 
       valid_lft forever preferred_lft forever
```

However if i run a container with docker i can't ping the address of the container spawned by kubernetes.
```
docker run --rm -ti base/archlinux /bin/bash
[root@87d9b164ffe9 /]# ip a show eth0
24: eth0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:0a:e9:01:08 brd ff:ff:ff:ff:ff:ff
    inet 10.233.1.8/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fee9:108/64 scope link 
       valid_lft forever preferred_lft forever
[root@87d9b164ffe9 /]# ping 10.233.1.5
PING 10.233.1.5 (10.233.1.5) 56(84) bytes of data.
From 10.233.1.8 icmp_seq=1 Destination Host Unreachable
```
Note : This container (run with docker) can ping another container launched the same way on another node.

The difference i can see comes from how the interfaces are created on the host, the kubernetes interfaces are not attached to the bridge cbr0.
```
21: cali09089e184d6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether c6:28:14:7c:36:cd brd ff:ff:ff:ff:ff:ff
    inet 10.115.77.87/32 scope global cali09089e184d6
       valid_lft forever preferred_lft forever
    inet6 fe80::c428:14ff:fe7c:36cd/64 scope link 
       valid_lft forever preferred_lft forever
25: veth4582dc5: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cbr0 state UP group default 
    link/ether 16:ca:4c:7e:e0:f0 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::14ca:4cff:fe7e:e0f0/64 scope link 
       valid_lft forever preferred_lft forever
```

When i look to the kubelet logs i get the following error log : 
```
Aug 28 09:34:54 kubenode-1 kubelet[29139]: I0828 09:34:54.047335   29139 exec.go:130] SetUpPod 'exec' network plugin output: Warning: '-format' is deprecated, it will be replaced by '--format' soon. See usage.
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Warning: '-format' is deprecated, it will be replaced by '--format' soon. See usage.
Aug 28 09:34:54 kubenode-1 kubelet[29139]: /tmp/_MEIc3W7lo/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
Aug 28 09:34:54 kubenode-1 kubelet[29139]: /tmp/_MEIc3W7lo/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Using ETCD_AUTHORITY=10.115.77.86:4001
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Using CALICOCTL_PATH=/usr/local/bin/calicoctl
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Using KUBE_API_ROOT=https://10.115.77.86:443/api/v1/
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Args: ['/usr/libexec/kubernetes/kubelet-plugins/net/exec/calico/calico', 'setup', 'default', 'redis-slave-nruvk', 'cc864fdf31cb3c14f44a14e13c144c41c7a2f06c053e4ab5942320cbc7a008e2']
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Executing Calico pod-creation hook
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Configuring docker container cc864fdf31cb3c14f44a14e13c144c41c7a2f06c053e4ab5942320cbc7a008e2
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Docker-assigned IP was 10.233.1.5
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Deleting eth0
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Configuring Calico networking.
Aug 28 09:34:54 kubenode-1 kubelet[29139]: IP 10.233.1.5 added to cc864fdf31cb3c14f44a14e13c144c41c7a2f06c053e4ab5942320cbc7a008e2
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Adding IP 10.115.77.87 to interface cali09001bb24d6
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Finished configuring network interface
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Failed to open auth_file ([Errno 2] No such file or directory: '/var/lib/kubelet/kubernetes_auth'), assuming insecure mode
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Traceback (most recent call last):
Aug 28 09:34:54 kubenode-1 kubelet[29139]: File "<string>", line 341, in <module>
Aug 28 09:34:54 kubenode-1 kubelet[29139]: File "<string>", line 46, in create
Aug 28 09:34:54 kubenode-1 kubelet[29139]: File "<string>", line 158, in _configure_profile
Aug 28 09:34:54 kubenode-1 kubelet[29139]: File "<string>", line 189, in _get_pod_config
Aug 28 09:34:54 kubenode-1 kubelet[29139]: File "<string>", line 220, in _get_api_path
Aug 28 09:34:54 kubenode-1 kubelet[29139]: File "/code/build/calico_kubernetes/out00-PYZ.pyz/json", line 338, in loads
Aug 28 09:34:54 kubenode-1 kubelet[29139]: File "/code/build/calico_kubernetes/out00-PYZ.pyz/json.decoder", line 366, in decode
Aug 28 09:34:54 kubenode-1 kubelet[29139]: File "/code/build/calico_kubernetes/out00-PYZ.pyz/json.decoder", line 384, in raw_decode
Aug 28 09:34:54 kubenode-1 kubelet[29139]: ValueError: No JSON object could be decoded
Aug 28 09:34:54 kubenode-1 kubelet[29139]: , exit status 255
```

Thanks for your help :)
Smana

**Comment by caseydavenport** [comment]
Hi Smana,

It's expected that Kubernetes pods which are networked using Calico should be attached to the caliXXXX interfaces (not the docker bridge) so I don't think that is your issue.

Looking at your Kubelet logs, it looks like you're configured to use HTTPS for accessing the Kubernetes API on its secure port (443), as indicated by this log:
```
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Using KUBE_API_ROOT=https://10.115.77.86:443/api/v1/
```

However, it doesn't look like you've configured auth on the Kubernetes node:
```
Aug 28 09:34:54 kubenode-1 kubelet[29139]: Failed to open auth_file ([Errno 2] No such file or directory: '/var/lib/kubelet/kubernetes_auth'), assuming insecure mode
```

I suspect this is causing the API request to fail, and Calico is attempting to interpret it as JSON (which fails).

At the moment, there are two ways to get this working (though #14 covers supporting more types of authentication):
- If your cluster supports it, switch to using the insecure port on the API. e.g `KUBE_API_ROOT=http://10.155.77.86:8080/api/v1`
- Create a token file at `/var/lib/kubelet/kubernetes_auth` which includes a BearerToken registered with the apiserver, which looks something like this:
```
{
  "BearerToken": "YOUR_TOKEN_HERE"
}
```

The plugin should probably be smarter about logging out when authentication types don't match - I've raised #29 to track improving diagnosability.

**Comment by Smana** [comment]
Hi Caseydavenport,
For the moment i chose the first option.
I'll work on securing the connection later.
Everything is working fine now.
Great tool, thank you!
