### ISSUE TITLE
Logging error in pycalico.ipam

### ISSUE THREAD

**Issue by Symmetric** [projectcalico/calico-kubernetes#98]
With calico-kubernetes v0.6.0, I'm seeing a logging error:

```
Nov 14 00:30:34 kubernetes-minion-1 kubelet[22990]: 2015-11-14 00:30:33,099 28521 [00bf223be692] INFO Configuring Calico network interface
Nov 14 00:30:34 kubernetes-minion-1 kubelet[22990]: 2015-11-14 00:30:33,148 28521 [00bf223be692] INFO Using Calico IPAM
Nov 14 00:30:34 kubernetes-minion-1 kubelet[22990]: Traceback (most recent call last):
Nov 14 00:30:34 kubernetes-minion-1 kubelet[22990]: File "/code/build/calico_kubernetes/out00-PYZ.pyz/logging", line 850, in emit
Nov 14 00:30:34 kubernetes-minion-1 kubelet[22990]: File "/code/build/calico_kubernetes/out00-PYZ.pyz/logging", line 723, in format
Nov 14 00:30:34 kubernetes-minion-1 kubelet[22990]: File "/code/build/calico_kubernetes/out00-PYZ.pyz/logging", line 467, in format
Nov 14 00:30:34 kubernetes-minion-1 kubelet[22990]: KeyError: 'identity'
Nov 14 00:30:34 kubernetes-minion-1 kubelet[22990]: Logged from file pycalico.ipam, line 403
```

Not sure if it's benign yet. Can you do a code read to see if we're setting the Formatter on the wrong log handler Alex?

**Comment by caseydavenport** [comment]
Fixed by #102
